### ISSUE TITLE
publish crate on `crates.io`

### ISSUE THREAD

**Issue by max397574** [nvim-treesitter/tree-sitter-query#22]
did you consider publishing this as a crate like e.g. [tree-sitter-swift](https://crates.io/crates/tree-sitter-swift)
this is required so rust projects depending on this can be published on `crates.io`

**Comment by max397574** [comment]
did you already publish it?
because I can't find it

**Comment by theHamsta** [comment]
See https://crates.io/crates/tree-sitter-query
