### ISSUE TITLE
`;` as a extra is causing some problems. 

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/tree-sitter-query#9]
@stsewd 

`;` as a extra is causing some problems. Try out `queries/c/highlights.scm`

https://user-images.githubusercontent.com/7189118/109558991-6885f200-7ada-11eb-810d-dc7f2223dc85.mp4

Boils down to `";"` is parsed as a comment

![image](https://user-images.githubusercontent.com/7189118/109559225-b4d13200-7ada-11eb-97a6-3228182a3693.png)

**Comment by stsewd** [comment]
Think comment node needs `token` and/or priority so isn't interfere with a normal string, I'll take a look later.
